const LIVES_UPDATE_INTERVAL_MINUTES = 20;

module.exports = {
  DISCORD_TOKEN:            process.env.DISCORD_TOKEN,
  LEADERBOARD_CHANNEL_ID:   process.env.LEADERBOARD_CHANNEL_ID,
  ADMIN_CHANNEL_ID:         process.env.ADMIN_CHANNEL_ID,
  WELCOME_CHANNEL_ID:       process.env.WELCOME_CHANNEL_ID,
  MEMBER_COUNT_CHANNEL_ID:  process.env.MEMBER_COUNT_CHANNEL_ID,
  LIVES_CHANNEL_ID:         process.env.LIVES_CHANNEL_ID,
  WEBSITE_RANKINGS_URL:     process.env.WEBSITE_RANKINGS_URL,
  TWITCH_CLIENT_ID:         process.env.TWITCH_CLIENT_ID,
  TWITCH_APP_TOKEN:         process.env.TWITCH_APP_TOKEN,
  LIVES_UPDATE_INTERVAL_MINUTES,
};
